#!/bin/bash

cd desktop
mkdir TopDir
cd TopDir
mkdir BottomDir
cd BottomDir



for i in {2..20}
do 
	touch File$i
	echo "My name is File$i" > File$i
	 if [ $i -eq 20 ]
                then echo "No next file" >> File$i 
         
		else echo "Next file's name will be $(($i+1))" >> File$i
	fi
	echo "created File$i"
done

cd files

for i in {2..20}
do
	echo "File$i"
	cat File$i
	echo "------------------------------"
	
done

files=`ls File*`
for f in $files
do 
	x=`grep '0\|2\|3' $f` 
	if [ -n "$x" ]
	then
		mv $f ..  
	fi 
done

